#!/usr/bin/env bash

# Check if all parameters are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$ssh_key" $SCP_OPTIONS "$path_to_file" "$username@$ip:~/"

# Check the exit code of the scp command
if [ $? -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
fi
