#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

# sudo apt-get -y update
# sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
# echo 'Hello World!' > /var/www/html/index.html
# sudo service nginx start

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 206011-web-01;/g' /etc/nginx/sites-available/default
sudo service nginx start
# Restart Nginx
# sudo service nginx restart

# Create index.html file with "Hello World!" content
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Ensure proper ownership and permissions for the index.html file
sudo chown www-data:www-data /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
