#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# redirects to another page
# Have a custom 404 page

apt-get update
apt-get install -y nginx

# Configure Nginx custom 404 page
cat > /etc/nginx/sites-available/custom_404 << EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location / {
        return 404;
        error_page 404 /404.html;
    }

    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

# Enable the custom 404 page site
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Create the custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Restart Nginx
service nginx restart
