#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times,
# but for the 9th iteration, displays Best School and then Hi on a new line.

num="0"
while [ $num -lt 10 ]
do
echo "Best School"
if [ $num -eq 8 ]
then echo "Hi"
fi
num=$((num+1))
done