#!/usr/bin/env bash
#  Bash script that displays the time for 12 hours and 59 minutes:

num1=1
num2=0

while [ "$num2" -le 12 ]
do
    echo "Hour: $num2"
    num1=1
    while [ "$num1" -le 59 ]
    do
        echo "$num1"
	num1=$((num1 + 1))
    done
    num2=$((num2 + 1))
done
num1=$num1
